services:
  - type: web
    name: gestionmr
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        value: postgresql://gestionmr_postgres_user:lnmJniS0U1X4WpXo8I5Te2SNH0hdcDOs@dpg-d7kne0ojs32c7382o750-a/gestionmr_postgres
      - key: SQLITE_PATH
        value: /app/data/cache.db
      - key: TOKEN_SECRET_KEY
        generateValue: true
      - key: BASE_URL
        value: https://gestionmr.onrender.com
      - key: MAILJET_API_KEY
        sync: false
      - key: MAILJET_SECRET_KEY
        sync: false
      - key: MAILJET_FROM_EMAIL
        sync: false
      - key: MAILJET_FROM_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_FOLDER
        value: ROMERITO
